// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: stock/stock.proto

package stock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockTicker_Subscribe_FullMethodName = "/stock.StockTicker/Subscribe"
)

// StockTickerClient is the client API for StockTicker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockTickerClient interface {
	Subscribe(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockResponse], error)
}

type stockTickerClient struct {
	cc grpc.ClientConnInterface
}

func NewStockTickerClient(cc grpc.ClientConnInterface) StockTickerClient {
	return &stockTickerClient{cc}
}

func (c *stockTickerClient) Subscribe(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StockResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockTicker_ServiceDesc.Streams[0], StockTicker_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StockRequest, StockResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockTicker_SubscribeClient = grpc.ServerStreamingClient[StockResponse]

// StockTickerServer is the server API for StockTicker service.
// All implementations must embed UnimplementedStockTickerServer
// for forward compatibility.
type StockTickerServer interface {
	Subscribe(*StockRequest, grpc.ServerStreamingServer[StockResponse]) error
	mustEmbedUnimplementedStockTickerServer()
}

// UnimplementedStockTickerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockTickerServer struct{}

func (UnimplementedStockTickerServer) Subscribe(*StockRequest, grpc.ServerStreamingServer[StockResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedStockTickerServer) mustEmbedUnimplementedStockTickerServer() {}
func (UnimplementedStockTickerServer) testEmbeddedByValue()                     {}

// UnsafeStockTickerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockTickerServer will
// result in compilation errors.
type UnsafeStockTickerServer interface {
	mustEmbedUnimplementedStockTickerServer()
}

func RegisterStockTickerServer(s grpc.ServiceRegistrar, srv StockTickerServer) {
	// If the following call pancis, it indicates UnimplementedStockTickerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockTicker_ServiceDesc, srv)
}

func _StockTicker_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StockRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StockTickerServer).Subscribe(m, &grpc.GenericServerStream[StockRequest, StockResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockTicker_SubscribeServer = grpc.ServerStreamingServer[StockResponse]

// StockTicker_ServiceDesc is the grpc.ServiceDesc for StockTicker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockTicker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stock.StockTicker",
	HandlerType: (*StockTickerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _StockTicker_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stock/stock.proto",
}
